CREATE TABLE banka_pazarlama_verisi (
    id SERIAL PRIMARY KEY,
    yas INT,
    meslek VARCHAR(50),
    medeni_durum VARCHAR(20),
    egitim VARCHAR(50),
    temerrut_durumu VARCHAR(10),
    konut_kredisi VARCHAR(10),
    tuketici_kredisi VARCHAR(10),
    iletisim_tipi VARCHAR(20),
    ay VARCHAR(20),
    gun VARCHAR(15),
    gorusme_suresi INT,
    kampanya_iletisim_sayisi INT,
    onceki_kampanyadan_sonra_gecen_gun INT,
    onceki_kampanya_iletisim_sayisi INT,
    onceki_kampanya_sonucu VARCHAR(20),
    is_gucu_degisim_orani FLOAT,
    tuketici_fiyat_endeksi FLOAT,
    tuketici_guven_endeksi FLOAT,
    euribor3ay FLOAT,
    calisan_sayisi FLOAT,
    hedef VARCHAR(10)
);